build(fix): proper postrelease hook

diff --git a/bin/release/postrelease b/bin/release/postrelease
--- a/bin/release/postrelease
+++ b/bin/release/postrelease
@@ -1,5 +1,31 @@
-#!/usr/bin/env bash
+#!/bin/bash
+
+REQUIRED_TOOLS=(
+  git
+)
+
+for TOOL in "${REQUIRED_TOOLS[@]}"; do
+  if ! command -v "${TOOL}" >/dev/null; then
+    echo "${TOOL} is required... "
+    exit 1
+  fi
+done
+
+# update version in citation configuration
+FILE=CITATION.cff
+if test -f "$FILE"; then
+  VERSION=$(node -pe 'require("./package.json")["version"]')
+  sed -i "s/^version: .*/version: ${VERSION}/" $FILE
+  DATE=$(date +%F)
+  sed -i "s/date-released: .*/date-released: ${DATE}/" $FILE
+  git add $FILE
+fi
+
+# adding data directory for new build information
+git add data/dnb
+git add README.md
+git commit --signoff --amend --no-edit
 
 # send all tags to remote
-git push --follow-tags origin main
-git push --tags
+git push origin main --follow-tags
+git push origin --tags
